### ISSUE TITLE
Route method

### ISSUE THREAD

**Issue by rayanwv** [AliasIO/Swiftlet#48]
Thank you for this framework, I really like it, and fit my requirements for my new project
I have quick question, how to handle different route method such as get, post, etc in controller?

**Comment by AliasIO** [comment]
Do you have an example of what you would like to do? Swiftlet has no opinion on how to handle POST requests, I typically use `$_POST` in combination with the built-in routing.

**Comment by rayanwv** [comment]
it is like when there is post request use controller 1: method A
if it is get request use controller 1: method B

**Comment by AliasIO** [comment]
There is no way to do that currently other than invoking a different method manually. If you want to have a go at implementing it yourself you can extend the `App` class and override the `dispatchController` method. I might have a look at adding this functionality as well.

**Comment by rayanwv** [comment]
I will try to implement it

**Comment by AliasIO** [comment]
Great, let me know how you progress and if you need any direction.

**Comment by AliasIO** [comment]
Have you made any progress with this? I'd be interested to know.

**Comment by rayanwv** [comment]
Honestly I couldn't figured out how to do it from scratch, I found many third party can handle it, but for learning purpose I would like to do it by myself

**Comment by AliasIO** [comment]
Do you have any examples of how others do it? I suppose it could be part of the route defenition like this:

```
protected $routes = array(
    'GET hello/world' => 'helloWorld',
    'POST hello/world' => 'helloWorldPost'
    );
```

This would only require some minor, non-breaking changes in `App::dispatchController()`.

**Comment by rayanwv** [comment]
two weeks ago I tried to implement something like this one
https://github.com/PatrickLouys/no-framework-tutorial/blob/master/05-router.md

I was think to pass the route definitions into the dispatchController

**Comment by kishor10d** [comment]
I have some issue with route.

suppose, I have ```HelloWorld``` namespace, controller file name is ```Index.php``` contain ```index()``` method.

When I hit url on my localhost as : ```localhost/swiftlet/public``` - it shows what I want.

If I have second method in same controller then what will be the expected url?
My code is given below

```
<?php

declare(strict_types=1);

namespace HelloWorld\Controllers;

use \HelloWorld\Models\Example as ExampleModel;
use \Swiftlet\Abstracts\Controller as ControllerAbstract;

class Index extends ControllerAbstract
{
	
	protected $title = 'Hello World!';

	public function index(array $args = [])
	{
		// Create a model instance, see /src/HelloWorld/Models/Example.php
		$example = new ExampleModel;

		// Get some data from the model and pass it to the view to display it
		$this->view->helloWorld = $example->getHelloWorld();
	}

	public function bar(array $args = [])
	{
		$this->title = "Foo, Bar!";

		echo "Foo, Bar!";

		die;
	}
}

```

What will be the url if I want to see the result of ```bar()``` method?

**Comment by AliasIO** [comment]
Does `localhost/swiftlet/public/index/bar` work?

**Comment by kishor10d** [comment]
@AliasIO : Sorry, it is very late.
Yes, I tried this! Currently, I am trying this, but not working.

**Comment by uaktags** [comment]
@kishor10d what issue do you get when you go to index/bar? If you're getting file/page can not be found, then it sounds like you're having a apache/nginx issue which is common with "pretty urls" for things like these.
